# Generated by Django 6.1.1 on 2026-09-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('group_manager', 'مدیر گروه'), ('mentor', 'منتور')], max_length=20, null=True, verbose_name='نقش'),
        ),
    ]
