# Generated by Django 6.1.1 on 2026-09-18 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام گروه')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('status', models.CharField(choices=[('pending_subscription', 'منتظر اشتراک'), ('pending_profile', 'منتظر تکمیل اطلاعات'), ('pending_mentor', 'منتظر منتور'), ('active', 'فعال'), ('inactive', 'غیرفعال')], default='pending_subscription', max_length=30, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_groups', to=settings.AUTH_USER_MODEL, verbose_name='مربی')),
            ],
        ),
    ]
