# Generated by Django 6.1.1 on 2026-09-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_manager_alter_group_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال باشد؟'),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('pending_subscription', 'منتظر اشتراک'), ('pending_profile', 'منتظر تکمیل اطلاعات'), ('pending_mentor', 'منتظر منتور')], default='pending_subscription', max_length=30, verbose_name='وضعیت'),
        ),
    ]
